### PR TITLE
regenerate df without time stamp modification

### LINKED ISSUE #37: getGPS fails if you convert ts to POSIX before running as in example
If you follow the examples in 5.5.2 and 5.5.3, and run `getGPS()`, you will get errors because `getGPS()` expects ts to not be POSIX.  You can fix this by running something like the code below first (leaving off the part converting the ts to POSIX timestamps from the code block immediately above the gps_index example).  

```
df.alltags.sub <- tbl.filtered.alltags %>% 
  filter(probability == 1) %>%
  collect() %>%
  as.data.frame()
```

This highlights an inconsistency that many functions need ts in timestamp format, but not `getGPS()`

This is also related to issue #36 in that there are other places in the book where df.alltags.sub is generated without converting ts to a POSIX timestamp.

### PR DESCRIPTION
**Pull request by plorch**
Since getGPS expects raw time stamps, we need to regenerate the flat data frame without modifying the time stamps as in previous example

This fixes #37

### CODE REVIEW

**Comment by steffilazerte** [comment]
Hi @plorch, thanks for taking the time to submit this PR. Unfortunately, we're planning on releasing the new docs sometime next week or the following, so we're going to focus on that right now. This repo will be archived once we do that so it just doesn't make sense for us to work on it right now (incorporating your fix means recompiling the book which would almost certainly start a bit of a snowball of other things to fix).

If you're interested/available we'd love to get any feedback you might have on the new version of the documentation. If that's of interest, I'll ping you when it's live. 

Thanks for being involved in the project!

**Comment by plorch** [comment]
Thanks Steffi.  I have done some bookdown stuff, so I know what you mean about snowballs.   I’d love to see the new documentation. 

     -Pat

***@***.***

**Comment by steffilazerte** [comment]
Awesome! I'll keep you posted, thanks.

**Comment by steffilazerte** [comment]
Hi @plorch!
It took us a while but the new documentation is live! Have a [look](https://motuswts.github.io/motus) and we'd love any [feed back](https://github.com/motuswts/motus/issues) you may have!

**Pull request closed without merging**
